language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo64-8.0
- Pharo64-7.0
- Pharo32-7.0
- Pharo32-6.1
before_deploy:
- cp "${SMALLTALK_CI_IMAGE}" "Stargate.image"
- cp "${SMALLTALK_CI_CHANGES}" "Stargate.changes"
- zip -q "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip" "Stargate.image" "Stargate.changes"
deploy:
  provider: releases
  api_key:
    secure: cEV5hDmvAXPQJerZ8l4+VGdjka1Juy/tcBuDpKUUJDPtBKBBRRKGDYMFqsfb4KlKWGbwSozUxmSG2S7DBk2TeF3CIJesVcoDkyKsagQxcl4+z3J3xuztNsTvgo1iYOlBpfLSfOB2NxL2fRyUknIoupl6Bsj92pf+olfX2BHwzp1rFLfJhz7onqHWscxr3IQMZRIeID33/uxpWOxFw9xSOZoXNNoKzrH/2Hb2xSQ5BS8qbTzjNWhGylJKuVbOP1EAieeC23BZcmmhNYmvlt3WjXi6HJ1htXJWOFR2DHiQ0CbpR7Y9RgGc/L30Jy/8AtUI++0IM2ojChxzqzbl8tQrhSLhV8ySIdvzmOiRQAwNxdnSV0dJNUMkQ1qe1DIj2qD5wRJz5UUJxtD2/xAL9G/fDt0RRLkNrHDu4xHZZnmRWk9OtP3Q2NNyFzqvmkB3gmvd3tgY2rSk9R2jrE4tujn0RaRm3NF3HEosNnv/umDxgPVi1Xy30P/G3d9jVS+F6MKyFjYWpbupgablSrf8v0l2MYZb9ICjWl7V1U5zQFfV5Meqt+CLTpc6gnrJYrJm7BB55vDQy6g6izBzmbNNG9DtEryLsD3zD52nQdvfFne7QX5E4WsLO/xXmcIctsKiTLGrOrPQO9/3R7m0FD8sKspLilv/PdzCfk3lR/EcHfg9+24=
  file: "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip"
  skip_cleanup: true
  on:
    repo: ba-st/Stargate
    tags: true
