name: 'GS64 Components Loading'
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
   component-loading:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        load-spec:
          - Application-Configuration
          - Application-Control
          - Application-Info
          - Core
          - Dependent-SUnit-Extensions
          - Deployment
          - Examples
          - HealthCheck
          - Metrics
          - JSON-RPC
    name: GS64 + ${{ matrix.load-spec }}
    steps:
      - uses: actions/checkout@v4
      - name: Load component in image
        uses: ba-st-actions/gs64-ci@v2
        with:
          project_name: 'Stargate'
          load_spec: 'Stargate-${{ matrix.load-spec }}'
