name: Pharo Groups Loading
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  group-loading:
    name: ${{ matrix.load-spec }}
    strategy:
      fail-fast: false
      matrix:
        load-spec:
          - app-config
          - app-control
          - app-info
          - core
          - dependent-sunit-extensions
          - deployment
          - development
          - examples
          - healthcheck
          - json-rpc
          - loggers
          - metrics
          - metrics-http
          - tests
          - tools
    uses: ./.github/workflows/loading-pharo-group.yml
    with:
      load-spec: ${{ matrix.load-spec }}
