name: 'GS64 Unit Tests'
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  unit-tests-3_7_1:
    runs-on: ubuntu-latest
    name: GS64 v3.7.1 Unit Tests
    steps:
      - uses: actions/checkout@v4
      - name: Load Image and Run Tests
        uses: ba-st-actions/gs64-ci@v3
        with:
          project_name: 'Stargate'
          run_tests: 'true'
